# https://docs.styleci.io/configuration
# https://styleci.readme.io/docs/presets
# https://styleci.readme.io/docs/fixers

preset: psr2

enabled:
  - multiline_array_trailing_comma
  - phpdoc_scalar
  - new_with_braces
  - no_empty_phpdoc
  - no_alias_functions
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_in_blank_line
  - return_type_declaration
  - short_scalar_cast
  - standardize_not_equals
  - trim_array_spaces
  - whitespace_after_comma_in_array
